routes:
  - match:
      host: us.sentry.io
      path_prefix_pattern: /organizations/{organization_id_or_slug}/
    route:
      dynamic_to: resolve_cell_from_organization
      default: us
  - match:
      host: us.sentry.io
      path_prefix_pattern: /cell/{cell_id}/
    route:
      dynamic_to: resolve_cell_from_id
  - match:
      host: de.sentry.io
      path_prefix_pattern: /organizations/{organization_id_or_slug}/
    route:
      to: de
